# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_plot2.ui'
#
# Created: Sat May 24 17:00:49 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_win_plot(object):
    def setupUi(self, win_plot):
        win_plot.setObjectName(_fromUtf8("win_plot"))
        win_plot.resize(1118, 662)
        self.centralwidget = QtGui.QWidget(win_plot)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_6.addWidget(self.label_19)
        self.radioButtonAllTime = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonAllTime.sizePolicy().hasHeightForWidth())
        self.radioButtonAllTime.setSizePolicy(sizePolicy)
        self.radioButtonAllTime.setChecked(False)
        self.radioButtonAllTime.setObjectName(_fromUtf8("radioButtonAllTime"))
        self.buttonGroup = QtGui.QButtonGroup(win_plot)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonAllTime)
        self.verticalLayout_6.addWidget(self.radioButtonAllTime)
        self.radioButtonSelectTime = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonSelectTime.sizePolicy().hasHeightForWidth())
        self.radioButtonSelectTime.setSizePolicy(sizePolicy)
        self.radioButtonSelectTime.setObjectName(_fromUtf8("radioButtonSelectTime"))
        self.buttonGroup.addButton(self.radioButtonSelectTime)
        self.verticalLayout_6.addWidget(self.radioButtonSelectTime)
        self.radioButtonMovingTime = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonMovingTime.setMaximumSize(QtCore.QSize(80, 20))
        self.radioButtonMovingTime.setChecked(True)
        self.radioButtonMovingTime.setObjectName(_fromUtf8("radioButtonMovingTime"))
        self.buttonGroup.addButton(self.radioButtonMovingTime)
        self.verticalLayout_6.addWidget(self.radioButtonMovingTime)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_7.addWidget(self.label_13)
        self.radioButtonAutoYT = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonAutoYT.setMaximumSize(QtCore.QSize(65, 20))
        self.radioButtonAutoYT.setChecked(True)
        self.radioButtonAutoYT.setObjectName(_fromUtf8("radioButtonAutoYT"))
        self.buttonGroup_2 = QtGui.QButtonGroup(win_plot)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButtonAutoYT)
        self.verticalLayout_7.addWidget(self.radioButtonAutoYT)
        self.radioButtonManualYT = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonManualYT.setMaximumSize(QtCore.QSize(65, 20))
        self.radioButtonManualYT.setChecked(False)
        self.radioButtonManualYT.setObjectName(_fromUtf8("radioButtonManualYT"))
        self.buttonGroup_2.addButton(self.radioButtonManualYT)
        self.verticalLayout_7.addWidget(self.radioButtonManualYT)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setIndent(3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_5.addWidget(self.label_14)
        self.radioButtonManualYP = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonManualYP.setObjectName(_fromUtf8("radioButtonManualYP"))
        self.buttonGroup_3 = QtGui.QButtonGroup(win_plot)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButtonManualYP)
        self.verticalLayout_5.addWidget(self.radioButtonManualYP)
        self.radioButtonAutoYP = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonAutoYP.setChecked(True)
        self.radioButtonAutoYP.setObjectName(_fromUtf8("radioButtonAutoYP"))
        self.buttonGroup_3.addButton(self.radioButtonAutoYP)
        self.verticalLayout_5.addWidget(self.radioButtonAutoYP)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(50, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.lineEditMinTime = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMinTime.sizePolicy().hasHeightForWidth())
        self.lineEditMinTime.setSizePolicy(sizePolicy)
        self.lineEditMinTime.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEditMinTime.setObjectName(_fromUtf8("lineEditMinTime"))
        self.verticalLayout_3.addWidget(self.lineEditMinTime)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(50, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.lineEditMaxTime = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMaxTime.sizePolicy().hasHeightForWidth())
        self.lineEditMaxTime.setSizePolicy(sizePolicy)
        self.lineEditMaxTime.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEditMaxTime.setObjectName(_fromUtf8("lineEditMaxTime"))
        self.verticalLayout_3.addWidget(self.lineEditMaxTime)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.lineEditMovingTime = QtGui.QLineEdit(self.centralwidget)
        self.lineEditMovingTime.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEditMovingTime.setObjectName(_fromUtf8("lineEditMovingTime"))
        self.verticalLayout_3.addWidget(self.lineEditMovingTime)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(50, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.lineEditMinYT = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMinYT.sizePolicy().hasHeightForWidth())
        self.lineEditMinYT.setSizePolicy(sizePolicy)
        self.lineEditMinYT.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEditMinYT.setObjectName(_fromUtf8("lineEditMinYT"))
        self.verticalLayout_4.addWidget(self.lineEditMinYT)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(50, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.lineEditMaxYT = QtGui.QLineEdit(self.centralwidget)
        self.lineEditMaxYT.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEditMaxYT.setObjectName(_fromUtf8("lineEditMaxYT"))
        self.verticalLayout_4.addWidget(self.lineEditMaxYT)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setMaximumSize(QtCore.QSize(50, 20))
        self.label_15.setLineWidth(0)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_10.addWidget(self.label_15)
        self.lineEditMinYP = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMinYP.sizePolicy().hasHeightForWidth())
        self.lineEditMinYP.setSizePolicy(sizePolicy)
        self.lineEditMinYP.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEditMinYP.setObjectName(_fromUtf8("lineEditMinYP"))
        self.verticalLayout_10.addWidget(self.lineEditMinYP)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setMaximumSize(QtCore.QSize(50, 20))
        self.label_16.setLineWidth(0)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_10.addWidget(self.label_16)
        self.lineEditMaxYP = QtGui.QLineEdit(self.centralwidget)
        self.lineEditMaxYP.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEditMaxYP.setObjectName(_fromUtf8("lineEditMaxYP"))
        self.verticalLayout_10.addWidget(self.lineEditMaxYP)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 4, -1, -1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setMaximumSize(QtCore.QSize(100, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_9.addWidget(self.label_12)
        self.checkBoxT1 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxT1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBoxT1.setChecked(True)
        self.checkBoxT1.setObjectName(_fromUtf8("checkBoxT1"))
        self.verticalLayout_9.addWidget(self.checkBoxT1)
        self.checkBoxT2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxT2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBoxT2.setChecked(True)
        self.checkBoxT2.setObjectName(_fromUtf8("checkBoxT2"))
        self.verticalLayout_9.addWidget(self.checkBoxT2)
        self.checkBoxT3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxT3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBoxT3.setChecked(True)
        self.checkBoxT3.setObjectName(_fromUtf8("checkBoxT3"))
        self.verticalLayout_9.addWidget(self.checkBoxT3)
        self.checkBoxT4 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxT4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBoxT4.setChecked(True)
        self.checkBoxT4.setObjectName(_fromUtf8("checkBoxT4"))
        self.verticalLayout_9.addWidget(self.checkBoxT4)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, 4, -1, -1)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setMaximumSize(QtCore.QSize(100, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_12.addWidget(self.label_18)
        self.checkBoxP0 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxP0.setMaximumSize(QtCore.QSize(180, 16777215))
        self.checkBoxP0.setChecked(True)
        self.checkBoxP0.setObjectName(_fromUtf8("checkBoxP0"))
        self.verticalLayout_12.addWidget(self.checkBoxP0)
        self.checkBoxP1 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxP1.setMaximumSize(QtCore.QSize(180, 16777215))
        self.checkBoxP1.setChecked(True)
        self.checkBoxP1.setObjectName(_fromUtf8("checkBoxP1"))
        self.verticalLayout_12.addWidget(self.checkBoxP1)
        self.checkBoxP2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxP2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.checkBoxP2.setChecked(True)
        self.checkBoxP2.setObjectName(_fromUtf8("checkBoxP2"))
        self.verticalLayout_12.addWidget(self.checkBoxP2)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_11.setContentsMargins(-1, 4, -1, -1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setMaximumSize(QtCore.QSize(70, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_11.addWidget(self.label_17)
        self.checkBoxLoadCell = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxLoadCell.setMaximumSize(QtCore.QSize(70, 16777215))
        self.checkBoxLoadCell.setCheckable(True)
        self.checkBoxLoadCell.setChecked(True)
        self.checkBoxLoadCell.setObjectName(_fromUtf8("checkBoxLoadCell"))
        self.verticalLayout_11.addWidget(self.checkBoxLoadCell)
        self.checkBoxScale = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxScale.setMaximumSize(QtCore.QSize(70, 16777215))
        self.checkBoxScale.setChecked(True)
        self.checkBoxScale.setObjectName(_fromUtf8("checkBoxScale"))
        self.verticalLayout_11.addWidget(self.checkBoxScale)
        self.checkBoxP3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxP3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.checkBoxP3.setChecked(False)
        self.checkBoxP3.setObjectName(_fromUtf8("checkBoxP3"))
        self.verticalLayout_11.addWidget(self.checkBoxP3)
        self.checkBoxP4 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxP4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.checkBoxP4.setChecked(False)
        self.checkBoxP4.setObjectName(_fromUtf8("checkBoxP4"))
        self.verticalLayout_11.addWidget(self.checkBoxP4)
        self.checkBoxP5 = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxP5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.checkBoxP5.setChecked(False)
        self.checkBoxP5.setObjectName(_fromUtf8("checkBoxP5"))
        self.verticalLayout_11.addWidget(self.checkBoxP5)
        self.checkBoxEvents = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxEvents.setChecked(True)
        self.checkBoxEvents.setObjectName(_fromUtf8("checkBoxEvents"))
        self.verticalLayout_11.addWidget(self.checkBoxEvents)
        self.btnClrData = QtGui.QPushButton(self.centralwidget)
        self.btnClrData.setMaximumSize(QtCore.QSize(100, 20))
        self.btnClrData.setObjectName(_fromUtf8("btnClrData"))
        self.verticalLayout_11.addWidget(self.btnClrData)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.qwtPlot = Qwt5.QwtPlot(self.centralwidget)
        self.qwtPlot.setMinimumSize(QtCore.QSize(300, 50))
        self.qwtPlot.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.verticalLayout_14.addWidget(self.qwtPlot)
        self.qwtPlot_3 = Qwt5.QwtPlot(self.centralwidget)
        self.qwtPlot_3.setMinimumSize(QtCore.QSize(300, 50))
        self.qwtPlot_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qwtPlot_3.setObjectName(_fromUtf8("qwtPlot_3"))
        self.verticalLayout_14.addWidget(self.qwtPlot_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelValve5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelValve5.setFont(font)
        self.labelValve5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValve5.setObjectName(_fromUtf8("labelValve5"))
        self.gridLayout.addWidget(self.labelValve5, 4, 5, 1, 1)
        self.labelValve6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelValve6.setFont(font)
        self.labelValve6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValve6.setObjectName(_fromUtf8("labelValve6"))
        self.gridLayout.addWidget(self.labelValve6, 4, 6, 1, 1)
        self.label_31 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 1, 6, 1, 1)
        self.label_30 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 1, 5, 1, 1)
        self.label_29 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 1, 4, 1, 1)
        self.checkBoxStopFill = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxStopFill.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkBoxStopFill.setObjectName(_fromUtf8("checkBoxStopFill"))
        self.gridLayout.addWidget(self.checkBoxStopFill, 6, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditFill = QtGui.QLineEdit(self.centralwidget)
        self.lineEditFill.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditFill.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditFill.setObjectName(_fromUtf8("lineEditFill"))
        self.horizontalLayout.addWidget(self.lineEditFill)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout.addWidget(self.label_20)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 1, 1, 1)
        self.labelIgniter = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelIgniter.setFont(font)
        self.labelIgniter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIgniter.setObjectName(_fromUtf8("labelIgniter"))
        self.gridLayout.addWidget(self.labelIgniter, 4, 7, 1, 1)
        self.pushButtonVentValve = QtGui.QPushButton(self.centralwidget)
        self.pushButtonVentValve.setObjectName(_fromUtf8("pushButtonVentValve"))
        self.gridLayout.addWidget(self.pushButtonVentValve, 2, 8, 1, 1)
        self.pushButtonValve2Close = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve2Close.setObjectName(_fromUtf8("pushButtonValve2Close"))
        self.gridLayout.addWidget(self.pushButtonValve2Close, 3, 2, 1, 1)
        self.pushButtonValve3Open = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve3Open.setObjectName(_fromUtf8("pushButtonValve3Open"))
        self.gridLayout.addWidget(self.pushButtonValve3Open, 2, 3, 1, 1)
        self.pushButtonValve3Close = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve3Close.setObjectName(_fromUtf8("pushButtonValve3Close"))
        self.gridLayout.addWidget(self.pushButtonValve3Close, 3, 3, 1, 1)
        self.pushButtonValve2Open = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve2Open.setObjectName(_fromUtf8("pushButtonValve2Open"))
        self.gridLayout.addWidget(self.pushButtonValve2Open, 2, 2, 1, 1)
        self.pushButtonValve1Open = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve1Open.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonValve1Open.setObjectName(_fromUtf8("pushButtonValve1Open"))
        self.gridLayout.addWidget(self.pushButtonValve1Open, 2, 1, 1, 1)
        self.pushButtonValve1Close = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve1Close.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonValve1Close.setObjectName(_fromUtf8("pushButtonValve1Close"))
        self.gridLayout.addWidget(self.pushButtonValve1Close, 3, 1, 1, 1)
        self.pushButtonValve4Open = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve4Open.setObjectName(_fromUtf8("pushButtonValve4Open"))
        self.gridLayout.addWidget(self.pushButtonValve4Open, 2, 4, 1, 1)
        self.pushButtonValve4Close = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve4Close.setObjectName(_fromUtf8("pushButtonValve4Close"))
        self.gridLayout.addWidget(self.pushButtonValve4Close, 3, 4, 1, 1)
        self.pushButtonIgniterOn = QtGui.QPushButton(self.centralwidget)
        self.pushButtonIgniterOn.setEnabled(False)
        self.pushButtonIgniterOn.setCheckable(False)
        self.pushButtonIgniterOn.setObjectName(_fromUtf8("pushButtonIgniterOn"))
        self.gridLayout.addWidget(self.pushButtonIgniterOn, 2, 7, 1, 1)
        self.pushButtonIgniterOff = QtGui.QPushButton(self.centralwidget)
        self.pushButtonIgniterOff.setEnabled(True)
        self.pushButtonIgniterOff.setObjectName(_fromUtf8("pushButtonIgniterOff"))
        self.gridLayout.addWidget(self.pushButtonIgniterOff, 3, 7, 1, 1)
        self.pushButtonValve5Open = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve5Open.setObjectName(_fromUtf8("pushButtonValve5Open"))
        self.gridLayout.addWidget(self.pushButtonValve5Open, 2, 5, 1, 1)
        self.pushButtonValve5Close = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve5Close.setObjectName(_fromUtf8("pushButtonValve5Close"))
        self.gridLayout.addWidget(self.pushButtonValve5Close, 3, 5, 1, 1)
        self.pushButtonValve6Open = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve6Open.setObjectName(_fromUtf8("pushButtonValve6Open"))
        self.gridLayout.addWidget(self.pushButtonValve6Open, 2, 6, 1, 1)
        self.pushButtonValve6Close = QtGui.QPushButton(self.centralwidget)
        self.pushButtonValve6Close.setObjectName(_fromUtf8("pushButtonValve6Close"))
        self.gridLayout.addWidget(self.pushButtonValve6Close, 3, 6, 1, 1)
        self.label_27 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 1, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 1, 7, 1, 1)
        self.labelValve1 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelValve1.sizePolicy().hasHeightForWidth())
        self.labelValve1.setSizePolicy(sizePolicy)
        self.labelValve1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelValve1.setFont(font)
        self.labelValve1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValve1.setObjectName(_fromUtf8("labelValve1"))
        self.gridLayout.addWidget(self.labelValve1, 4, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 1, 1, 1, 1)
        self.labelValve4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelValve4.setFont(font)
        self.labelValve4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValve4.setObjectName(_fromUtf8("labelValve4"))
        self.gridLayout.addWidget(self.labelValve4, 4, 4, 1, 1)
        self.pushButtonPurge = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPurge.setObjectName(_fromUtf8("pushButtonPurge"))
        self.gridLayout.addWidget(self.pushButtonPurge, 3, 8, 1, 1)
        self.labelValve2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelValve2.setFont(font)
        self.labelValve2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValve2.setObjectName(_fromUtf8("labelValve2"))
        self.gridLayout.addWidget(self.labelValve2, 4, 2, 1, 1)
        self.labelValve3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelValve3.setFont(font)
        self.labelValve3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValve3.setObjectName(_fromUtf8("labelValve3"))
        self.gridLayout.addWidget(self.labelValve3, 4, 3, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(200, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(999999, 400))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_13.addWidget(self.textBrowser)
        self.btnClrText = QtGui.QPushButton(self.centralwidget)
        self.btnClrText.setObjectName(_fromUtf8("btnClrText"))
        self.verticalLayout_13.addWidget(self.btnClrText)
        self.checkBoxSaveData = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxSaveData.sizePolicy().hasHeightForWidth())
        self.checkBoxSaveData.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxSaveData.setFont(font)
        self.checkBoxSaveData.setChecked(True)
        self.checkBoxSaveData.setObjectName(_fromUtf8("checkBoxSaveData"))
        self.verticalLayout_13.addWidget(self.checkBoxSaveData)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_7.addWidget(self.label_24)
        self.lineEditLaunchDuration = QtGui.QLineEdit(self.centralwidget)
        self.lineEditLaunchDuration.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditLaunchDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditLaunchDuration.setObjectName(_fromUtf8("lineEditLaunchDuration"))
        self.horizontalLayout_7.addWidget(self.lineEditLaunchDuration)
        self.label_25 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_7.addWidget(self.label_25)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_13)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.pushButtonArm = QtGui.QPushButton(self.centralwidget)
        self.pushButtonArm.setObjectName(_fromUtf8("pushButtonArm"))
        self.verticalLayout_8.addWidget(self.pushButtonArm)
        self.labelArmed = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArmed.sizePolicy().hasHeightForWidth())
        self.labelArmed.setSizePolicy(sizePolicy)
        self.labelArmed.setMinimumSize(QtCore.QSize(95, 0))
        self.labelArmed.setMaximumSize(QtCore.QSize(99999, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelArmed.setFont(font)
        self.labelArmed.setTextFormat(QtCore.Qt.PlainText)
        self.labelArmed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelArmed.setObjectName(_fromUtf8("labelArmed"))
        self.verticalLayout_8.addWidget(self.labelArmed)
        self.pushButtonLaunch = QtGui.QPushButton(self.centralwidget)
        self.pushButtonLaunch.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLaunch.sizePolicy().hasHeightForWidth())
        self.pushButtonLaunch.setSizePolicy(sizePolicy)
        self.pushButtonLaunch.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLaunch.setFont(font)
        self.pushButtonLaunch.setObjectName(_fromUtf8("pushButtonLaunch"))
        self.verticalLayout_8.addWidget(self.pushButtonLaunch)
        self.labelCountdownMode = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labelCountdownMode.setFont(font)
        self.labelCountdownMode.setObjectName(_fromUtf8("labelCountdownMode"))
        self.verticalLayout_8.addWidget(self.labelCountdownMode)
        self.labelCountdown = QtGui.QLabel(self.centralwidget)
        self.labelCountdown.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labelCountdown.setFont(font)
        self.labelCountdown.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCountdown.setObjectName(_fromUtf8("labelCountdown"))
        self.verticalLayout_8.addWidget(self.labelCountdown)
        self.pushButtonAbort = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAbort.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAbort.setFont(font)
        self.pushButtonAbort.setObjectName(_fromUtf8("pushButtonAbort"))
        self.verticalLayout_8.addWidget(self.pushButtonAbort)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_1 = QtGui.QLabel(self.centralwidget)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout_2.addWidget(self.label_1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_2.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_2.addWidget(self.label_23)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        win_plot.setCentralWidget(self.centralwidget)

        self.retranslateUi(win_plot)
        QtCore.QMetaObject.connectSlotsByName(win_plot)

    def retranslateUi(self, win_plot):
        win_plot.setWindowTitle(_translate("win_plot", "ROCKET!!", None))
        self.label_19.setText(_translate("win_plot", "Time Axis", None))
        self.radioButtonAllTime.setText(_translate("win_plot", "All Time", None))
        self.radioButtonSelectTime.setText(_translate("win_plot", "Manual Time", None))
        self.radioButtonMovingTime.setText(_translate("win_plot", "Moving Time", None))
        self.label_13.setText(_translate("win_plot", "Temperature Axis", None))
        self.radioButtonAutoYT.setText(_translate("win_plot", "Auto Y", None))
        self.radioButtonManualYT.setText(_translate("win_plot", "Manual Y", None))
        self.label_14.setText(_translate("win_plot", "Pressure Axis", None))
        self.radioButtonManualYP.setText(_translate("win_plot", "Manual Y", None))
        self.radioButtonAutoYP.setText(_translate("win_plot", "Auto Y", None))
        self.label.setText(_translate("win_plot", "Min Time:", None))
        self.lineEditMinTime.setText(_translate("win_plot", "0", None))
        self.label_8.setText(_translate("win_plot", "Max Time:", None))
        self.lineEditMaxTime.setText(_translate("win_plot", "1", None))
        self.label_11.setText(_translate("win_plot", "Moving Time:", None))
        self.lineEditMovingTime.setText(_translate("win_plot", "60", None))
        self.label_10.setText(_translate("win_plot", "Min Y:", None))
        self.lineEditMinYT.setText(_translate("win_plot", "0", None))
        self.label_9.setText(_translate("win_plot", "Max Y:", None))
        self.lineEditMaxYT.setText(_translate("win_plot", "5", None))
        self.label_15.setText(_translate("win_plot", "Min Y:", None))
        self.lineEditMinYP.setText(_translate("win_plot", "0", None))
        self.label_16.setText(_translate("win_plot", "Max Y:", None))
        self.lineEditMaxYP.setText(_translate("win_plot", "5", None))
        self.label_12.setText(_translate("win_plot", "Temperture Sensors", None))
        self.checkBoxT1.setText(_translate("win_plot", "Temp 1: Chamber Wall", None))
        self.checkBoxT2.setText(_translate("win_plot", "Temp 2: Precumbustion", None))
        self.checkBoxT3.setText(_translate("win_plot", "Temp 3: Gas Tank", None))
        self.checkBoxT4.setText(_translate("win_plot", "Temp 4: Tank Wall", None))
        self.label_18.setText(_translate("win_plot", "Pressure Sensors", None))
        self.checkBoxP0.setText(_translate("win_plot", "Pin 1: Feed Line Beofre Oriface", None))
        self.checkBoxP1.setText(_translate("win_plot", "Pin 2: Chamber", None))
        self.checkBoxP2.setText(_translate("win_plot", "Pin 3: Tank", None))
        self.label_17.setText(_translate("win_plot", "Other Devices", None))
        self.checkBoxLoadCell.setText(_translate("win_plot", "Load Cell", None))
        self.checkBoxScale.setText(_translate("win_plot", "Scale", None))
        self.checkBoxP3.setText(_translate("win_plot", "Pin 3", None))
        self.checkBoxP4.setText(_translate("win_plot", "Pin 4", None))
        self.checkBoxP5.setText(_translate("win_plot", "Pin 5", None))
        self.checkBoxEvents.setText(_translate("win_plot", "Events", None))
        self.btnClrData.setText(_translate("win_plot", "Clear Data", None))
        self.labelValve5.setText(_translate("win_plot", "Closed", None))
        self.labelValve6.setText(_translate("win_plot", "Closed", None))
        self.label_31.setText(_translate("win_plot", "Nitrogen Purge", None))
        self.label_30.setText(_translate("win_plot", "N20 Vent", None))
        self.label_29.setText(_translate("win_plot", "Flight Tank Vent", None))
        self.checkBoxStopFill.setText(_translate("win_plot", "Stop Filling at:", None))
        self.lineEditFill.setText(_translate("win_plot", "730", None))
        self.label_20.setText(_translate("win_plot", "PSI", None))
        self.labelIgniter.setText(_translate("win_plot", "Closed", None))
        self.pushButtonVentValve.setText(_translate("win_plot", "0.5 Sec\n"
"Vent Valve", None))
        self.pushButtonValve2Close.setText(_translate("win_plot", "Close Valve 2", None))
        self.pushButtonValve3Open.setText(_translate("win_plot", "Open Valve 3", None))
        self.pushButtonValve3Close.setText(_translate("win_plot", "Close Valve 3", None))
        self.pushButtonValve2Open.setText(_translate("win_plot", "Open Valve 2", None))
        self.pushButtonValve1Open.setText(_translate("win_plot", "Open Valve 1", None))
        self.pushButtonValve1Close.setText(_translate("win_plot", "Close Valve 1", None))
        self.pushButtonValve4Open.setText(_translate("win_plot", "Open Valve 4", None))
        self.pushButtonValve4Close.setText(_translate("win_plot", "Close Valve 4", None))
        self.pushButtonIgniterOn.setText(_translate("win_plot", "Igniter On", None))
        self.pushButtonIgniterOff.setText(_translate("win_plot", "Igniter Off", None))
        self.pushButtonValve5Open.setText(_translate("win_plot", "Open Valve 5", None))
        self.pushButtonValve5Close.setText(_translate("win_plot", "Close Valve 5", None))
        self.pushButtonValve6Open.setText(_translate("win_plot", "Open Valve 6", None))
        self.pushButtonValve6Close.setText(_translate("win_plot", "Close Valve 6", None))
        self.label_27.setText(_translate("win_plot", "Upstream Main", None))
        self.label_28.setText(_translate("win_plot", "Downstream Main", None))
        self.label_32.setText(_translate("win_plot", "Igniter", None))
        self.labelValve1.setText(_translate("win_plot", "Closed", None))
        self.label_26.setText(_translate("win_plot", "Fill", None))
        self.labelValve4.setText(_translate("win_plot", "Closed", None))
        self.pushButtonPurge.setText(_translate("win_plot", "Purge System", None))
        self.labelValve2.setText(_translate("win_plot", "Closed", None))
        self.labelValve3.setText(_translate("win_plot", "Closed", None))
        self.btnClrText.setText(_translate("win_plot", "Clear History", None))
        self.checkBoxSaveData.setText(_translate("win_plot", "Save Data", None))
        self.label_24.setText(_translate("win_plot", "Launch Duration:", None))
        self.lineEditLaunchDuration.setText(_translate("win_plot", "10", None))
        self.label_25.setText(_translate("win_plot", "Sec", None))
        self.pushButtonArm.setText(_translate("win_plot", "Arm?", None))
        self.labelArmed.setText(_translate("win_plot", "Not Armed", None))
        self.pushButtonLaunch.setText(_translate("win_plot", "LAUNCH", None))
        self.labelCountdownMode.setText(_translate("win_plot", "Waiting", None))
        self.labelCountdown.setText(_translate("win_plot", "--", None))
        self.pushButtonAbort.setText(_translate("win_plot", "ABORT", None))
        self.label_1.setText(_translate("win_plot", "Pressure 0: 9999 PSI", None))
        self.label_2.setText(_translate("win_plot", "Pressure 1: 9999 PSI", None))
        self.label_3.setText(_translate("win_plot", "Pressure 2: 9999 PSI", None))
        self.label_4.setText(_translate("win_plot", "Temp 1 (CW): 9999 C", None))
        self.label_5.setText(_translate("win_plot", "Temp 2 (PC): 9999 C", None))
        self.label_6.setText(_translate("win_plot", "Temp 3 (GT): 9999 C", None))
        self.label_21.setText(_translate("win_plot", "Temp 4 (TW): 9999 C", None))
        self.label_22.setText(_translate("win_plot", "Scale: 9999 kg", None))
        self.label_23.setText(_translate("win_plot", "Load Cell: 9999 N", None))
        self.label_7.setText(_translate("win_plot", "Sample Rate: 000 Hz", None))

from PyQt4 import Qwt5
